sudo: required
language: python
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install build-essential docker-ce
jobs:
  include:
    - python: 3.7
      env: TOXENV=format
      stage: test
    - python: 3.7
      env: TOXENV=py37
      stage: test
    - python: 3.9
      env: TOXENV=py39
      stage: test
    - python: 3.7
      env: TOXENV=format DEPLOY=true
      stage: deploy
      if: tag IS present
install: pip install -U importlib_metadata tox-travis
script: tox

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true
    condition: $DEPLOY = true
  distributions: bdist_wheel
