sudo: required
language: python
dist: jammy
services:
  - docker
before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update -y
  - mkdir -vp ~/.docker/cli-plugins/
  - curl --silent -L "https://github.com/docker/buildx/releases/download/v0.11.0/buildx-v0.11.0.linux-amd64" > ~/.docker/cli-plugins/docker-buildx
  - chmod a+x ~/.docker/cli-plugins/docker-buildx
#  - sudo apt-get -y install build-essential
#  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install build-essential docker-ce
jobs:
  include:
    - python: 3.8
      env: TOXENV=format
      stage: test
    - python: 3.8
      env: TOXENV=py38
      stage: test
    - python: 3.11
      env: TOXENV=py311
      stage: test
    - python: 3.11
      env: TOXENV=format DEPLOY=true
      stage: deploy
      if: tag IS present
install: pip install -U importlib_metadata tox-travis
script: tox

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true
    condition: $DEPLOY = true
  distributions: bdist_wheel
