sudo: required
language: python
services:
  - docker
python:
  - "3.7"
  - "3.9"
install: pip install tox-travis
script: tox --travis-after

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true
  distributions: bdist_wheel
