sudo: required
language: python
services:
  - docker
jobs:
  include:
    - python: 3.7
      env: TOXENV=format
      stage: test
    - python: 3.7
      env: TOXENV=py37
      stage: test
    - python: 3.9
      env: TOXENV=py39
      stage: test
    - python: 3.7
      env: TOXENV=format DEPLOY=true
      stage: deploy
      if: tag IS present
install: pip install tox-travis
script: tox

deploy:
  provider: pypi
  user: $PYPI_USERNAME
  password: $PYPI_PASSWORD
  skip_existing: true
  on:
    tags: true
    condition: $DEPLOY = true
  distributions: bdist_wheel
